services:
  redis:
    image: redis:alpine3.22
    container_name: redis
    restart: on-failure
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - 6379:6379
    networks:
      - shared_net

networks:
  shared_net:
    external: true
